# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(FFFFF7)
$foreground = rgb(090B0D)
$color0 = rgb(FFFFF7)
$color1 = rgb(787B5D)
$color2 = rgb(6B8D99)
$color3 = rgb(803027)
$color4 = rgb(56463A)
$color5 = rgb(28424C)
$color6 = rgb(101216)
$color7 = rgb(090B0D)
$color8 = rgb(828469)
$color9 = rgb(A1A47D)
$color10 = rgb(8FBCCC)
$color11 = rgb(AB4034)
$color12 = rgb(735E4D)
$color13 = rgb(355865)
$color14 = rgb(15181E)
$color15 = rgb(030404)
