# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #090B0D
background         #FFFFF7
cursor             #4C636D

active_tab_foreground     #FFFFF7
active_tab_background     #090B0D
inactive_tab_foreground   #090B0D
inactive_tab_background   #FFFFF7

active_border_color   #090B0D
inactive_border_color #FFFFF7
bell_border_color     #787B5D

color0      #FFFFF7
color1		#787B5D
color2		#6B8D99
color3		#803027
color4		#56463A
color5		#28424C
color6		#101216
color7		#090B0D
color8		#828469
color9		#A1A47D
color10		#8FBCCC
color11		#AB4034
color12		#735E4D
color13		#355865
color14		#15181E
color15		#030404
