-- Generated by nwg-displays on 2026-09-14 at 14:59:06. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.0",
    position = "3644x1080",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "3306x0",
    scale = 1,
    vrr = 0
})
