-- Generated by nwg-displays on 2026-07-01 at 20:38:03. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1366x768@60.0",
    position = "3759x201",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1366x768@59.79",
    position = "2393x201",
    scale = 1.0
})
